### ISSUE TITLE
Drip breaks with Django 1.8

### ISSUE THREAD

**Issue by simonv3** [zapier/django-drip#51]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/simon/src/uklo/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/simon/src/uklo/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/simon/src/uklo/venv/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/simon/src/uklo/venv/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/simon/src/uklo/venv/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/simon/src/uklo/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/simon/src/uklo/venv/lib/python3.4/site-packages/drip/models.py", line 7, in <module>
    from drip.utils import get_user_model
  File "/Users/simon/src/uklo/venv/lib/python3.4/site-packages/drip/utils.py", line 5, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named 'django.db.models.related'
```

From a quick search, there's some ideas as to what could be wrong here and how to fix it (but it's beyond me at the moment):

https://github.com/treyhunner/django-simple-history/issues/156

**Comment by rwillmer** [comment]
I've got a version that seems to work. I'll run it for a few days and then send a Pull Request, once I've removed the debugging.

Anyone who's needs it before then, you can take a look at https://github.com/rwillmer/django-drip

**Comment by kronok** [comment]
@rwillmer It almost works, but doesn't seem to be going through the manytomany's "child" fields, it just lists the parent. I can't seem to figure out what's going on.

**Comment by rwillmer** [comment]
If you can give me a testcase that fails, I'll look into it
Rachel

kronok wrote:

**Comment by alexphelps** [comment]
@rwillmer your fork almost works for me but I'm unable to run `manage.py test` it gives this error. 
```django.db.utils.ProgrammingError: relation "auth_user" does not exist```
